### ISSUE TITLE
Sentence_dump.p file missing in resource

### ISSUE THREAD

**Issue by namalasantosh** [SaujanyaReddy/Aspect-Based-Sentiment-Analysis-IRE-Major-Project#2]
the file sentence_dump.p  file is missing in the resource provided. Can you pls provide the same.
aspect_dump_new.p file also missing in resource

thank you 
santosh

**Comment by SaujanyaReddy** [comment]
Hi

I used restaurant reviews from semeval 2014. http://metashare.ilsp.gr:8080/repository/browse/semeval-2014-absa-restaurant-reviews-train-data/479d18c0625011e38685842b2b6a04d72cb57ba6c07743b9879d1a04e72185b8/ 

above is the link to the xml data. if you run the client.py it will give you sentence_dump.p 

i will add the file sentence_dump.p  and aspect_dump_new.p for the above data 

thank you 
saujanya
